local vars = require("vars")
require("keybinds")

-- Catppuccin Latte palette
local latte = require("catppuccin-latte")

-- Helper: Catppuccin hex + alpha -> rgba(...)
local function rgba(hex, alpha)
    return string.format("rgba(%s%s)", hex, alpha)
end

-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
hl.config({ autogenerated = false }) -- remove this line to remove the warning

---- MONITORS ----
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "1.2",
})

---- AUTOSTART ----
-- Пример автозапуска, если нужен:
-- hl.on("hyprland.start", function()
--     hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

---- ENVIRONMENT VARIABLES ----
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

---- LOOK AND FEEL ----
hl.config({
    general = {
        gaps_in  = 6,
        gaps_out = 18,
        border_size = 2,

        -- Catppuccin Latte border colors
        col = {
            active_border = {
                colors = {
                    rgba(latte.mauveAlpha, "ee"),
                    rgba(latte.lavenderAlpha, "dd"),
                    rgba(latte.blueAlpha, "cc"),
                },
                angle = 45,
            },
            inactive_border = rgba(latte.overlay0Alpha, "aa"),
        },

        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = 12,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 0.97,

        shadow = {
            enabled = true,
            range = 14,
            render_power = 3,

            -- Мягкая тень в оттенке Catppuccin text
            -- Формат: 0xAARRGGBB
            color = tonumber("55" .. latte.textAlpha, 16),
        },

        blur = {
            enabled = true,
            size = 5,
            passes = 2,
            vibrancy = 0.20,
        },
    },

    animations = {
        enabled = true,
    },
})

---- ANIMATION CURVES ----
-- Более плавные кривые для Catppuccin Latte
hl.curve("latte_standard", {
    type = "bezier",
    points = {
        { 0.40, 0.00 },
        { 0.20, 1.00 },
    },
})

hl.curve("latte_out", {
    type = "bezier",
    points = {
        { 0.16, 1.00 },
        { 0.30, 1.00 },
    },
})

hl.curve("latte_in", {
    type = "bezier",
    points = {
        { 0.25, 0.10 },
        { 0.25, 1.00 },
    },
})

hl.curve("latte_spring", {
    type = "spring",
    mass = 1,
    stiffness = 160,
    dampening = 24,
})

---- ANIMATIONS ----
-- Если анимации покажутся слишком медленными, увеличь speed на 0.5–1.5
hl.animation({ leaf = "global",        enabled = true, speed = 6.2, bezier = "latte_standard" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.2, bezier = "latte_out" })

hl.animation({ leaf = "windows",       enabled = true, speed = 4.4, spring = "latte_spring" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.0, spring = "latte_spring", style = "popin 92%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 3.6, bezier = "latte_out",    style = "popin 94%" })

hl.animation({ leaf = "fadeIn",        enabled = true, speed = 3.2, bezier = "latte_in" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 3.0, bezier = "latte_out" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.8, bezier = "latte_standard" })

hl.animation({ leaf = "layers",        enabled = true, speed = 4.2, bezier = "latte_out" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3.9, bezier = "latte_out", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 3.2, bezier = "latte_out", style = "fade" })

hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 3.3, bezier = "latte_in" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 3.0, bezier = "latte_out" })

hl.animation({ leaf = "workspaces",    enabled = true, speed = 3.8, bezier = "latte_standard", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 3.4, bezier = "latte_in",       style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 3.6, bezier = "latte_out",      style = "fade" })

hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 6.0, bezier = "latte_standard" })

---- LAYOUTS ----
hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

---- MISC ----
hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },
})

---- INPUT ----
hl.config({
    input = {
        kb_layout  = "us,ru",
        kb_variant = "",
        kb_model   = "",
        kb_options = "grp:caps_toggle",
        kb_rules   = "",

        follow_mouse = 1,
        sensitivity = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Пример настройки конкретного устройства.
-- Раскомментируй и замени имя устройства при необходимости.
-- hl.device({
--     name = "epic-mouse-v1",
--     sensitivity = -0.5,
-- })

---- WINDOWS AND WORKSPACES ----
local suppressMaximizeRule = hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})